### ISSUE TITLE
Fizzy/npfs cannot read biom file

### ISSUE THREAD

**Issue by feargalr** [EESI/Fizzy#3]
Hi, 

I've been trying to use this software but I'm unable to get fizzy or npfs to read in any biom files. Including those of my own making (in json format) which returns the following error 

Traceback (most recent call last):
  File "/usr/local/bin/fizzy", line 441, in <module>
    sys.exit(main())
  File "/usr/local/bin/fizzy", line 418, in main
    data, samples, features, feature_ids = load_biom(args)
  File "/usr/local/bin/fizzy", line 85, in load_biom
    features.append(json.dumps(sid["metadata"]["taxonomy"]))
TypeError: 'NoneType' object has no attribute '__getitem__'

The tutorial data you provided does not work either as they are in HDF5 format and not JSON which is the most up to date biom specification, which fizzy does not seem able to read. Also the file names in the tutorial are different to what's actually provided in the dataset..

I've tried added metadata and taxonomy into the biom file, in JSON format but it's still not able to be read in. 

Any tips on making a biom file for use with fizzy?

Thanks

**Comment by mutantturkey1** [comment]
If you made this biom by hand, you might be running into problems. It appears that the sid['metadata'] dictionary doesn't contain 'taxonomy' element, based on this traceback. If you have a  biom file we could run this locally and test it to ensure it's valid, and that our fizzy implementation is acting appropriately.

**Comment by feargalr** [comment]
I'd prefer not to exchange anything for confidentiality reasons, but I can always make some example data if it comes to it.

How would you recommend constructing a biom file for use in Fizzy? 

I thought I added a taxonomy element in the metadata dictionary, but perhaps it didn't add correctly so I'll double check this.

Biom is a useful format of course, but for simplicity it could be great to just have the option of using a tab delimited count matrix, especially since fizzy/npfs provide the option of giving mapping file/label..

**Comment by feargalr** [comment]
This is working for me now. For future users, this worked for me by adding metadata and taxonomy data to the biom file. When adding taxonomy data beware of the following issue that I ran into

https://github.com/biocore/biom-format/issues/530

And be sure to have the biom file in JSON, not HDF5. 

Thanks

**Comment by mutantturkey** [comment]
Let's update our documentation to help future users be more clear about
specific requirements
