### ISSUE TITLE
error with BIOM and error with csv file

### ISSUE THREAD

**Issue by gailrosen** [EESI/Fizzy#4]
With BIOM file, I get this error:

Traceback (most recent call last):
  File "/home/gailr/fs_pcoa/Fizzy/src/npfs", line 452, in <module>
    sys.exit(main())
  File "/home/gailr/fs_pcoa/Fizzy/src/npfs", line 417, in main
    data, samples, features, feature_ids = load_biom(args)
  File "/home/gailr/fs_pcoa/Fizzy/src/npfs", line 80, in load_biom
    samples.append(sid["id"])
KeyError: 'id'

With .csv file, I get this error:

[gailr@proteusa01 fs_ambulance]$ more ambulance_surface_mifs2.sh.o320158
Error: sample  AE0003 was not found in map file.

Sending you files privately.

**Comment by gditzler** [comment]
Is sample `AE0003` in the map file?

**Comment by gailrosen** [comment]
Yes.....
